<?php

namespace AppBundle\Repository;

/**
 * MarketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarketRepository extends \Doctrine\ORM\EntityRepository
{
}
